server:
  port: 8080

loadstar:
  # project root is now passed as API parameter (?root=...)

spring:
  devtools:
    restart:
      enabled: true
  web:
    resources:
      static-locations: file:../frontend/dist/,classpath:/static/
