server:
  port: 8080

loadstar:
  project-path: ${LOADSTAR_PROJECT_PATH:C:/bono/MCP/GIT/loadstar_ui}

spring:
  devtools:
    restart:
      enabled: true
  web:
    resources:
      static-locations: file:../frontend/dist/,classpath:/static/
